# Generated by Django 5.2.5 on 2025-08-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='mentor',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Lower number shows first'),
        ),
    ]
