# Generated by Django 5.2.5 on 2025-08-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mentor_options_mentor_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('All Courses', 'All Courses'), ('Computer Science', 'Computer Science'), ('Civil Tools', 'Civil Tools'), ('Mechanical Tools', 'Mechanical Tools'), ('Architecture', 'Architecture'), ('Specialized', 'Specialized'), ('Networking', 'Networking'), ('Creative Arts', 'Creative Arts')], max_length=100),
        ),
    ]
