# Generated by Django 5.2.5 on 2025-08-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mentor_options_mentor_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(unique=True)),
                ('image', models.ImageField(upload_to='hero_slides/')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
