# Generated by Django 5.2.5 on 2025-08-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_course_category'),
        ('main', '0005_heroslide'),
    ]

    operations = [
    ]
