# Generated by Django 5.2.5 on 2025-08-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['category', '-created_at']},
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('corporate', 'Corporate'), ('defence', 'Defence'), ('government', 'Government')], default='corporate', max_length=50),
        ),
    ]
