# Generated by Django 5.2.5 on 2025-08-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_gallery_options_gallery_category'),
        ('main', '0006_merge_0005_alter_course_category_0005_heroslide'),
    ]

    operations = [
    ]
