# Generated by Django 5.2.5 on 2025-08-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20250826_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('corporate', 'Corporate'), ('defence', 'Defence'), ('government', 'Government'), ('water', 'Water'), ('fire', 'Fire')], default='corporate', max_length=50),
        ),
    ]
