# Generated by Django 5.2.5 on 2025-09-11 06:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_gallery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('development', 'Development'), ('corporate_defence_trainings', 'Corporate & Defence Trainings'), ('outbound_trainings', 'Outbound Trainings'), ('ministry_of_defence', 'Ministry of Defence'), ('student_trainings', 'Student Trainings'), ('achievements', 'Achievements & Moments')], default='corporate', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='gallery/'),
        ),
    ]
