# Generated by Django 5.2.5 on 2025-10-17 09:18

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_mentor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('development', 'Development'), ('corporate_defence_trainings', 'Corporate & Defence Trainings'), ('outbound_trainings', 'Outbound Trainings'), ('ministry_of_defence', 'Ministry of Defence'), ('student_trainings', 'Student Trainings'), ('achievements', 'Achievements & Moments')], default='corporate_defence_trainings', max_length=50),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='hero_slides/'),
        ),
    ]
