# Generated by Django 5.2.5 on 2025-11-03 07:51

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_course_image_alter_gallery_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(help_text='The main image for the product.', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/')),
                ('features', models.TextField(help_text='List each feature on a new line or use bullet points. This will be split into a list on the frontend.')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
