# Generated by Django 5.2.5 on 2025-11-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('software_development', 'Software Development'), ('lab_setup', 'Lab Setup'), ('product_development', 'Product Development')], default='software_development', help_text='The service section where this product will be displayed.', max_length=50),
        ),
    ]
